receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
  prometheus:
    endpoint: "0.0.0.0:8888"
  tempo:
    endpoint: "http://localhost:3200"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
    traces:
      receivers: [otlp]
      exporters: [tempo]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
